/* Breezus NFL GM App v4.1 - current roster intelligence */
(function(){
'use strict';
if(window.__gm41Booted)return; window.__gm41Booted=true;
const $=id=>document.getElementById(id),safe=(f,d)=>{try{return f()}catch{return d}},n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=x=>{x=String(x||'').toUpperCase();return ['DST','D/ST','DEFENSE'].includes(x)?'DEF':x};
const SEASON=2026, POS=['QB','RB','WR','TE','DEF'];
const NFL_TEAMS=new Set('ARI ATL BAL BUF CAR CHI CIN CLE DAL DEN DET GB HOU IND JAX KC LAC LAR LV MIA MIN NE NO NYG NYJ PHI PIT SEA SF TB TEN WAS'.split(' '));
const RETIRED_NAMES=new Set(['todd gurley','andrew luck','ben roethlisberger','eli manning','philip rivers','frank gore','marshawn lynch','adrian peterson','rob gronkowski','julian edelman','antonio brown','aj green','dez bryant','cam newton','jj watt','j.j. watt','drew brees','matt ryan','aaron donald','leonard fournette','le'veon bell']);
let schedule=[],projections={},tab='home',loaded=false;
function roster(){return safe(()=>S.rosters.find(r=>String(r.owner_id)===String(S.me.user_id))||S.mine,null)}
function ids(){return[...new Set((roster()?.players||[]).map(String).filter(Boolean))]}
function starters(){return new Set((roster()?.starters||[]).map(String).filter(x=>x&&x!=='0'))}
function p(id){return safe(()=>window.player(id)||S.players[String(id)],{})}
function pos(id){return norm(safe(()=>window.position(id),p(id).position))}
function team(id){return String(p(id).team||'').toUpperCase()}
function pname(id){const q=p(id);return safe(()=>window.pn(id),q.full_name||[q.first_name,q.last_name].filter(Boolean).join(' ')||id)}
function playerHealth(id){return String(safe(()=>window.playerStatus(id)?.label,p(id).status||'AVAILABLE')).toUpperCase()}
function proj(id){const x=projections[String(id)];if(!x)return n(safe(()=>window.expectedPoints(id),0));const s=safe(()=>S.league?.scoring_settings||{},{}),r=n(s.rec),key=r>=.9?'pts_ppr':r>=.4?'pts_half_ppr':'pts_std';return Number.isFinite(Number(x[key]))?n(x[key]):n(safe(()=>window.expectedPoints(id),0))}
function currentPlayer(id){const q=p(id),name=pname(id).toLowerCase(),st=String(q.status||'').toUpperCase(),h=playerHealth(id),t=team(id);if(RETIRED_NAMES.has(name))return false;if(st.includes('RETIRED')||h.includes('RETIRED'))return false;if(q.active===false&&h!=='AVAILABLE'&&!t)return false;if(q.injury_status==='RET')return false;if(pos(id)==='DEF')return NFL_TEAMS.has(t);return !!id}
function usableWaiverPlayer(x){const id=String(x?.player_id||'');if(!id)return false;const name=String(x.full_name||[x.first_name,x.last_name].filter(Boolean).join(' ')||'').toLowerCase();const position=norm(x.position);if(!POS.includes(position)||RETIRED_NAMES.has(name))return false;const st=String(x.status||'').toUpperCase();if(st.includes('RETIRED')||st.includes('PRACTICE SQUAD'))return false;const h=String(safe(()=>window.playerStatus(id)?.label,'AVAILABLE')).toUpperCase();if(h.includes('RETIRED'))return false;if(position==='DEF')return NFL_TEAMS.has(String(x.team||'').toUpperCase());return true}
function game(id){const w=n(S.week||S.league?.week,1),t=team(id);return schedule.find(g=>n(g.season)===SEASON&&n(g.week)===w&&(String(g.home_team||'').toUpperCase()===t||String(g.away_team||'').toUpperCase()===t))||null}
function matchup(id){const g=game(id);if(!g)return'BYE';const t=team(id),o=String(g.home_team||'').toUpperCase()===t?g.away_team:g.home_team;return'VS '+String(o||'').toUpperCase()}
function slots(){return safe(()=>S.league?.roster_positions||[],[]).filter(x=>x&&x!=='BN'&&x!=='IR')}
function eligible(id,s){const q=pos(id);return s==='FLEX'?['RB','WR','TE'].includes(q):q===s}
function optimise(){const data=ids().map(id=>({id,v:proj(id),pos:pos(id),health:playerHealth(id)})).filter(x=>x.pos&&x.health!=='OUT'),ss=slots();let best={score:-Infinity,assign:[]};function walk(i,used,a,total){if(i===ss.length){if(total>best.score)best={score:total,assign:a.slice()};return}const slot=ss[i],cs=data.filter(x=>!used.has(x.id)&&eligible(x.id,slot)).sort((a,b)=>b.v-a.v).slice(0,30);if(!cs.length)return;for(const x of cs){used.add(x.id);a.push({id:x.id,slot});walk(i+1,used,a,total+x.v);a.pop();used.delete(x.id)}}walk(0,new Set(),[],0);return best}
function lineupRows(){const r=roster(),a=[...(r?.starters||[])].map(String),ss=slots();return ss.map((slot,i)=>({slot,id:a[i]&&a[i]!=='0'?a[i]:null}))}
function bench(){const s=starters();return ids().filter(id=>!s.has(id)&&pos(id)&&currentPlayer(id)).sort((a,b)=>proj(b)-proj(a))}
function replacementFor(id,opt){const oldPos=pos(id);const assigned=opt.assign.map(a=>String(a.id));const candidates=ids().filter(x=>x!==id&&!assigned.includes(String(x))&&currentPlayer(x)&&playerHealth(x)!=='OUT'&&eligible(x, slots()[Math.max(0,lineupRows().findIndex(r=>String(r.id)===String(id)))]));return candidates.sort((a,b)=>proj(b)-proj(a))[0]||null}
function allFreeAgents(){const own=new Set(S.rosters.flatMap(r=>r.players||[]).map(String)),adds=new Map((S.adds||[]).map(x=>[String(x.player_id),n(x.count)]));return Object.values(S.players||{}).filter(usableWaiverPlayer).filter(x=>!own.has(String(x.player_id))).map(x=>({id:String(x.player_id),pos:norm(x.position),v:proj(String(x.player_id)),trend:n(adds.get(String(x.player_id))),team:String(x.team||'FA').toUpperCase()})).filter(x=>x.v>0||x.trend>0)}
function topByPosition(position){return allFreeAgents().filter(x=>x.pos===position).sort((a,b)=>b.v-a.v||b.trend-a.trend).slice(0,10)}
function trendingByPosition(position){return allFreeAgents().filter(x=>x.pos===position).sort((a,b)=>b.trend-a.trend||b.v-a.v).slice(0,10)}
function playerRow(id,slot){return`<div class="g41-player"><div>${slot?`<span class="g41-slot">${esc(slot)}</span>`:''}<b>${esc(pname(id))}</b><span class="g41-muted">${esc(pos(id))} · ${esc(team(id)||'FA')} · ${esc(matchup(id))} · ${esc(playerHealth(id))}</span></div><strong>${proj(id).toFixed(1)}</strong></div>`}
function css(){if($('gm41-style'))return;const s=document.createElement('style');s.id='gm41-style';s.textContent=`#gm40.g41{font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif}#gm40.g41 .g41-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.g41-card{background:#fff;border:1px solid #e6e0da;border-radius:17px;padding:15px}.g41-player{display:flex;justify-content:space-between;gap:10px;align-items:center;padding:10px 0;border-top:1px solid #eee9e5}.g41-player:first-child{border-top:0}.g41-slot{font-size:9px;font-weight:950;background:#f0ece8;border-radius:6px;padding:4px 6px;margin-right:7px}.g41-muted{display:block;color:#746e79;font-size:10px;margin-top:3px}.g41-note{font-size:11px;color:#746e79;line-height:1.45}.g41-pill{display:inline-block;padding:4px 8px;border-radius:99px;font-size:9px;font-weight:950}.g41-green{background:#e4faf3;color:#146b55}.g41-amber{background:#fff1d1;color:#82590e}.g41-red{background:#fdeaea;color:#9d2929}.g41-blue{background:#eaf0ff;color:#294da7}.g41-section{margin-top:12px}.g41-action{padding:12px;border:1px solid #e6e0da;border-radius:12px;background:#faf9f7;margin-top:8px}.g41-top10{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.g41-top10 h3{margin:0}.g41-rank{font-size:10px;color:#746e79;font-weight:900}.g41-tabs{display:flex;gap:6px;overflow:auto;margin-bottom:10px}.g41-tab{border:1px solid #e0dad5;background:#fff;border-radius:10px;padding:8px 11px;font-weight:900;white-space:nowrap}.g41-tab.active{background:#17002f;color:#fff}@media(max-width:850px){#gm40.g41 .g41-grid{grid-template-columns:1fr}.g41-top10{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function home(){const r=roster(),s=starters(),o=optimise(),current=ids().filter(id=>s.has(id)).reduce((a,id)=>a+proj(id),0),gain=Math.max(0,o.score-current);return`<div class="g40-hero"><div class="g40-card"><div class="g40-label">CURRENT LINEUP</div><div class="g40-kpi">${current.toFixed(1)}</div><span class="g40-pill ${gain>.5?'g40-blue':'g40-green'}">${gain>.5?'+'+gain.toFixed(1)+' available':'LINEUP OK'}</span></div><div class="g40-card"><div class="g40-label">ROSTER</div><div class="g40-kpi">${ids().length}</div><div class="g40-muted">${s.size} starters · ${bench().length} actual bench</div></div></div><div class="g41-grid"><div class="g41-card"><h3>What to do this week</h3>${gain>.5?`<div class="g41-action"><span class="g41-pill g41-blue">LINEUP</span><b> Review ${gain.toFixed(1)} projected points available</b><div class="g41-note">Open Lineup to see exactly who should replace whom.</div></div>`:''}${ids().filter(id=>playerHealth(id)==='OUT').map(id=>`<div class="g41-action"><span class="g41-pill g41-red">OUT</span><b>${esc(pname(id))}</b><div class="g41-note">Unavailable. Lineup will identify the best replacement.</div></div>`).join('')||(!gain?'<div class="g41-note">No immediate lineup move detected.</div>':'')}</div><div class="g41-card"><h3>Current starters</h3>${lineupRows().map(x=>x.id?playerRow(x.id,x.slot):`<div class="g41-action"><span class="g41-slot">${esc(x.slot)}</span> Empty slot</div>`).join('')}</div><div class="g41-card"><h3>Actual bench</h3>${bench().slice(0,10).map(id=>playerRow(id)).join('')||'<div class="g41-note">No actual bench players loaded.</div>'}</div></div>`}
function lineup(){const o=optimise(),best=new Map(o.assign.map(x=>[String(x.id),x.slot]));return`<div class="g41-card"><div class="g40-title"><div><h2>Lineup Decisions</h2><div class="g41-note">Every current starter gets a direct replacement recommendation when the model sees a better legal option.</div></div><span class="g41-pill g41-green">BEST ${o.score.toFixed(1)}</span></div>${lineupRows().map(x=>{if(!x.id)return`<div class="g41-action"><span class="g41-slot">${esc(x.slot)}</span> Empty slot</div>`;const inBest=best.has(String(x.id));const rep=!inBest?replacementFor(x.id,o):null;const h=playerHealth(x.id);return`<div class="g41-action"><div class="g40-title"><div><span class="g41-slot">${esc(x.slot)}</span><b>${esc(pname(x.id))}</b><span class="g41-muted">${pos(x.id)} · ${proj(x.id).toFixed(1)} projected · ${esc(matchup(x.id))} · ${esc(h)}</span></div><span class="g41-pill ${inBest?'g41-green':'g41-red'}">${h==='OUT'?'REPLACE':inBest?'KEEP':'REPLACE'}</span></div>${h==='OUT'?`<div class="g41-note">Inactive. Best legal replacement: ${rep?`<b>${esc(pname(rep))}</b> (${proj(rep).toFixed(1)} projected)`: 'no legal replacement found yet'}.</div>`:!inBest&&rep?`<div class="g41-note"><b>Replace with ${esc(pname(rep))}</b> · ${proj(rep).toFixed(1)} projected vs ${proj(x.id).toFixed(1)} · ${esc(pos(rep))}. This move is part of the best legal lineup.</div>`:inBest?`<div class="g41-note">Keep. This player is included in the best legal lineup from your current roster.</div>`:'<div class="g41-note">Review this starter. No stronger legal replacement was found.</div'}</div>`}).join('')}<div class="g41-section"><h3>Actual Bench</h3>${bench().map(id=>playerRow(id)).join('')||'<div class="g41-note">No actual bench players found.</div>'}</div></div>`}
function matchupView(){return`<div class="g41-card"><div class="g40-title"><div><h2>Weekly Matchup</h2><div class="g41-note">Matchup context is shown here. Start/sit decisions stay in Lineup.</div></div></div><div class="g41-grid">${POS.map(q=>`<div class="g41-card"><div class="g40-label">${q}</div>${ids().filter(id=>starters().has(id)&&pos(id)===q).map(id=>playerRow(id)).join('')||'<div class="g41-note">No starter</div>'}</div>`).join('')}</div></div>`}
function waivers(){const sections=POS.map(q=>{const top=topByPosition(q),trend=trendingByPosition(q);return`<div class="g41-card"><div class="g40-title"><h3>${q==='DEF'?'DEF':q}</h3><span class="g41-pill g41-blue">TOP 10</span></div>${top.map((x,i)=>`<div class="g41-player"><div><span class="g41-rank">${i+1}</span> <b>${esc(pname(x.id))}</b><span class="g41-muted">${x.team} · ${x.trend} adds</span></div><strong>${x.v.toFixed(1)}</strong></div>`).join('')||'<div class="g41-note">No current candidates.</div>'}<div class="g41-section"><h4>Trending adds</h4>${trend.slice(0,10).map((x,i)=>`<div class="g41-player"><div><span class="g41-rank">${i+1}</span> <b>${esc(pname(x.id))}</b><span class="g41-muted">${x.team} · ${x.trend} adds · ${x.v.toFixed(1)} projected</span></div><span class="g41-pill g41-green">TRENDING</span></div>`).join('')||'<div class="g41-note">No current trending adds.</div>'}</div></div>`}).join('');return`<div class="g41-card"><div class="g40-title"><div><h2>Waiver GM</h2><div class="g41-note">Top 10 available players at every position plus a separate trending list. Owned players and retired/non-current players are excluded.</div></div><span class="g41-pill g41-green">CURRENT 2026</span></div><div class="g41-top10">${sections}</div></div>`}
function rosterView(){return`<div class="g41-card"><div class="g40-title"><div><h2>Roster</h2><div class="g41-note">Live Sleeper roster only. No historical free agents or retired players are shown.</div></div></div>${ids().filter(currentPlayer).sort((a,b)=>{const sa=starters().has(a),sb=starters().has(b);return Number(sb)-Number(sa)||proj(b)-proj(a)}).map(id=>playerRow(id,starters().has(id)?'STARTER':'BENCH')).join('')}</div>`}
function placeholder(title,text){return`<div class="g41-card"><h2>${title}</h2><p class="g41-note">${text}</p><div class="g41-action">This surface is reserved for the dedicated ${title.toLowerCase()} engine. No duplicate legacy panels are loaded.</div></div>`}
function render(){const root=$('gm40'),m=$('g40-main');if(!root||!m)return;root.classList.add('g41');document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));m.innerHTML=tab==='home'?home():tab==='lineup'?lineup():tab==='matchup'?matchupView():tab==='waivers'?waivers():tab==='roster'?rosterView():placeholder(tab==='trades'?'Trade Finder':'Dynasty',tab==='trades'?'Trade analysis belongs here only.':'Long-term player value belongs here only.');$('g40-status').textContent=`Week ${n(S.week||S.league?.week,1)} · ${ids().length} roster players · ${loaded?'CURRENT DATA':'loading'}`}
async function loadData(){loaded=false;render();try{const r=await fetch(`/api/research?season=${SEASON}&week=${n(S.week||S.league?.week,1)}`,{cache:'no-store'});if(r.ok){const j=await r.json();projections=j.projections||{}}}catch(e){}try{const r=await fetch(`/api/nfl-schedule?season=${SEASON}`,{cache:'no-store'});if(r.ok){const j=await r.json();schedule=Array.isArray(j)?j:(j.games||[])}}catch(e){}loaded=true;render()}
function boot(){css();const old=$('gm40');if(old){old.classList.add('g41');}loadData();setTimeout(()=>{render()},1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
