/* Breezus NFL GM App v4.0 - unified application shell */
(function(){
'use strict';
if(window.__gm40Booted)return;window.__gm40Booted=true;
const $=id=>document.getElementById(id),safe=(f,d)=>{try{return f()}catch{return d}},n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=x=>{x=String(x||'').toUpperCase();return ['DST','D/ST','DEFENSE'].includes(x)?'DEF':x};
const season=2026;let schedule=[],projections={},tab='home',ready=false;
function roster(){return safe(()=>S.rosters.find(r=>String(r.owner_id)===String(S.me.user_id))||S.mine,null)}
function ids(){return[...new Set((roster()?.players||[]).map(String).filter(Boolean))]}
function st(){return new Set((roster()?.starters||[]).map(String))}
function p(id){return safe(()=>window.player(id)||S.players[String(id)],{})}
function pos(id){return norm(safe(()=>window.position(id),p(id).position))}
function team(id){return String(p(id).team||'').toUpperCase()}
function pname(id){const q=p(id);return safe(()=>window.pn(id),q.full_name||[q.first_name,q.last_name].filter(Boolean).join(' ')||id)}
function health(id){return String(safe(()=>window.playerStatus(id)?.label,'AVAILABLE')).toUpperCase()}
function proj(id){const x=projections[String(id)];if(!x)return n(safe(()=>window.expectedPoints(id),0));const s=safe(()=>S.league?.scoring_settings||{},{}),r=n(s.rec),key=r>=.9?'pts_ppr':r>=.4?'pts_half_ppr':'pts_std';return Number.isFinite(Number(x[key]))?n(x[key]):n(safe(()=>window.expectedPoints(id),0))}
function game(id){const w=n(S.week||S.league?.week,1),t=team(id);return schedule.find(g=>n(g.season)===season&&n(g.week)===w&&(String(g.home_team||'').toUpperCase()===t||String(g.away_team||'').toUpperCase()===t))||null}
function matchup(id){const g=game(id);if(!g)return 'BYE';const t=team(id),o=String(g.home_team||'').toUpperCase()===t?g.away_team:g.home_team;return 'VS '+String(o||'').toUpperCase()}
function slots(){return safe(()=>S.league?.roster_positions||[],[]).filter(x=>x&&x!=='BN'&&x!=='IR')}
function eligible(id,s){const q=pos(id);return s==='FLEX'?['RB','WR','TE'].includes(q):q===s}
function optimise(){const data=ids().map(id=>({id,v:proj(id),pos:pos(id),health:health(id)})).filter(x=>x.pos&&x.health!=='OUT'),ss=slots();let best={score:-Infinity,assign:[]};function walk(i,used,a,total){if(i===ss.length){if(total>best.score)best={score:total,assign:a.slice()};return}const slot=ss[i],cs=data.filter(x=>!used.has(x.id)&&eligible(x.id,slot)).sort((a,b)=>b.v-a.v).slice(0,24);if(!cs.length)return;for(const x of cs){used.add(x.id);a.push({id:x.id,slot});walk(i+1,used,a,total+x.v);a.pop();used.delete(x.id)}}walk(0,new Set(),[],0);return best}
function rows(){const r=roster(),a=[...(r?.starters||[])].map(String),ss=slots();return ss.map((slot,i)=>({slot,id:a[i]&&a[i]!=='0'?a[i]:null}))}
function bench(){const s=st();return ids().filter(id=>!s.has(id)&&pos(id)).sort((a,b)=>proj(b)-proj(a))}
function playerRow(id,slot){return `<div class="g40-player"><div>${slot?`<span class="g40-slot">${esc(slot)}</span>`:''}<b>${esc(pname(id))}</b><span class="g40-muted">${esc(pos(id))} · ${esc(team(id)||'FA')} · ${esc(matchup(id))} · ${esc(health(id))}</span></div><strong>${proj(id).toFixed(1)}</strong></div>`}
function css(){if($('gm40-style'))return;const s=document.createElement('style');s.id='gm40-style';s.textContent=`#gm40{font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif;background:#f4f2ef;color:#17131d;min-height:100vh;margin:-14px;padding:14px}#gm40 *{box-sizing:border-box}.g40-wrap{max-width:1320px;margin:auto}.g40-top{background:linear-gradient(135deg,#17002f,#32174f);color:#fff;border-radius:22px;padding:18px;display:flex;justify-content:space-between;align-items:center;gap:12px}.g40-brand{display:flex;gap:12px;align-items:center}.g40-logo{width:48px;height:48px;border-radius:15px;background:#21c69c;display:grid;place-items:center;font-size:25px}.g40-top h1{margin:0;font-size:23px}.g40-top p{margin:4px 0 0;color:#d8d0e0;font-size:11px}.g40-run{background:#21c69c;color:#17002f;border:0;border-radius:11px;padding:12px 16px;font-weight:950}.g40-tabs{display:flex;gap:6px;overflow:auto;margin:12px 0}.g40-tab{border:1px solid #e0dad5;background:#fff;border-radius:11px;padding:10px 13px;font-weight:900;white-space:nowrap}.g40-tab.active{background:#17002f;color:#fff}.g40-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.g40-card{background:#fff;border:1px solid #e6e0da;border-radius:17px;padding:15px}.g40-hero{display:grid;grid-template-columns:1.35fr .65fr;gap:10px;margin-bottom:10px}.g40-label{font-size:10px;color:#746e79;font-weight:900;text-transform:uppercase}.g40-kpi{font-size:30px;font-weight:950}.g40-muted{display:block;color:#746e79;font-size:10px;margin-top:3px}.g40-title{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:10px}.g40-title h2,.g40-title h3{margin:0}.g40-pill{padding:4px 8px;border-radius:99px;font-size:9px;font-weight:950}.g40-green{background:#e4faf3;color:#146b55}.g40-amber{background:#fff1d1;color:#82590e}.g40-red{background:#fdeaea;color:#9d2929}.g40-blue{background:#eaf0ff;color:#294da7}.g40-player{display:flex;justify-content:space-between;gap:10px;align-items:center;padding:11px 0;border-top:1px solid #eee9e5}.g40-player:first-child{border-top:0}.g40-slot{font-size:9px;font-weight:950;background:#f0ece8;border-radius:6px;padding:4px 6px;margin-right:7px}.g40-row{padding:11px 0;border-top:1px solid #eee9e5}.g40-empty{padding:18px;background:#faf9f7;border-radius:12px;color:#746e79;text-align:center}.g40-note{font-size:11px;color:#746e79;line-height:1.45}.g40-old{display:none!important}@media(max-width:850px){#gm40{margin:-9px;padding:9px}.g40-top{flex-direction:column;align-items:stretch}.g40-run{width:100%}.g40-grid{grid-template-columns:repeat(2,1fr)}.g40-hero{grid-template-columns:1fr}}@media(max-width:520px){.g40-grid{grid-template-columns:1fr}.g40-top h1{font-size:20px}}`;document.head.appendChild(s)}
function hideOld(){document.querySelectorAll('.hero,.metrics,.layout,#status').forEach(x=>x.classList.add('g40-old'));document.querySelectorAll('[id^="gm-"],[id^="gm2"],[id^="gm25"],[id^="gm26"],[id^="gm27"],[id^="gm31"]').forEach(x=>x.classList.add('g40-old'))}
function shell(){let root=$('gm40');if(root)return;root=document.createElement('div');root.id='gm40';root.innerHTML=`<div class="g40-wrap"><header class="g40-top"><div class="g40-brand"><div class="g40-logo">🏈</div><div><h1>Breezus NFL GM</h1><p id="g40-status">Connecting to Sleeper...</p></div></div><button class="g40-run" id="g40-run">REFRESH GM</button></header><nav class="g40-tabs">${[['home','GM Home'],['lineup','Lineup'],['matchup','Matchup'],['waivers','Waivers'],['trades','Trades'],['dynasty','Dynasty'],['roster','Roster']].map(x=>`<button class="g40-tab" data-tab="${x[0]}">${x[1]}</button>`).join('')}</nav><main id="g40-main"></main></div>`;document.body.insertBefore(root,document.body.firstChild);root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});$('g40-run').onclick=()=>loadData()}
function home(){const r=roster(),s=st(),opt=optimise(),current=ids().filter(id=>s.has(id)).reduce((a,id)=>a+proj(id),0),gain=Math.max(0,opt.score-current),b=bench();return `<div class="g40-hero"><div class="g40-card"><div class="g40-label">CURRENT LINEUP</div><div class="g40-kpi">${current.toFixed(1)}</div><span class="g40-pill ${gain>.5?'g40-blue':'g40-green'}">${gain>.5?'+'+gain.toFixed(1)+' available':'LINEUP OK'}</span></div><div class="g40-card"><div class="g40-label">ROSTER</div><div class="g40-kpi">${ids().length}</div><div class="g40-muted">${s.size} starters · ${b.length} actual bench</div></div></div><div class="g40-grid"><div class="g40-card"><div class="g40-title"><h3>What to do this week</h3><span class="g40-pill g40-green">GM</span></div>${gain>.5?`<div class="g40-row"><b>Optimise the lineup</b><span class="g40-muted">Model sees ${gain.toFixed(1)} projected points available.</span></div>`:''}${b[0]?`<div class="g40-row"><b>Bench watch</b><span class="g40-muted">${esc(pname(b[0]))} is your highest projected bench player.</span></div>`:''}${ids().filter(id=>health(id)==='OUT').map(id=>`<div class="g40-row"><b>Inactive</b><span class="g40-muted">${esc(pname(id))} needs a replacement.</span></div>`).join('')||(!gain&& !b[0]?'<div class="g40-empty">No immediate GM action detected.</div>':'')}</div><div class="g40-card"><div class="g40-title"><h3>Current starters</h3><span class="g40-pill g40-blue">FULL</span></div>${rows().map(x=>x.id?playerRow(x.id,x.slot):`<div class="g40-row"><span class="g40-slot">${esc(x.slot)}</span> Empty slot</div>`).join('')}</div><div class="g40-card"><div class="g40-title"><h3>Actual bench</h3><span class="g40-pill g40-amber">LIVE</span></div>${b.slice(0,8).map(id=>playerRow(id)).join('')||'<div class="g40-empty">No bench players loaded.</div>'}</div><div class="g40-card"><div class="g40-title"><h3>Data health</h3></div><div class="g40-row"><b>Sleeper roster</b><span>${r?'OK':'WAITING'}</span></div><div class="g40-row"><b>Schedule</b><span>${schedule.length?'OK':'FALLBACK'}</span></div><div class="g40-row"><b>Projections</b><span>${Object.keys(projections).length?'OK':'FALLBACK'}</span></div></div></div>`}
function lineup(){const o=optimise(),idsO=new Set(o.assign.map(x=>String(x.id)));return `<div class="g40-card"><div class="g40-title"><div><h2>Your Lineup</h2><div class="g40-note">This is the only lineup decision view. It contains your actual starters, actual bench and the legal GM optimisation.</div></div><span class="g40-pill g40-green">BEST ${o.score.toFixed(1)}</span></div>${rows().map(x=>x.id?`<div class="g40-player"><div><span class="g40-slot">${esc(x.slot)}</span><b>${esc(pname(x.id))}</b><span class="g40-muted">${pos(x.id)} · ${matchup(x.id)} · ${health(x.id)}</span></div><span><strong>${proj(x.id).toFixed(1)}</strong><br><span class="g40-pill ${idsO.has(String(x.id))?'g40-green':'g40-amber'}">${idsO.has(String(x.id))?'GM KEEP':'REVIEW'}</span></span></div>`:`<div class="g40-row"><span class="g40-slot">${esc(x.slot)}</span> Empty slot</div>`).join('')}<div class="g40-title" style="margin-top:16px"><h3>Actual Bench</h3><span class="g40-pill g40-amber">NO FAKE EMPTY SLOTS</span></div>${bench().map(id=>playerRow(id)).join('')||'<div class="g40-empty">No actual bench players found.</div>'}</div>`}
function matchupView(){return `<div class="g40-card"><div class="g40-title"><div><h2>Weekly Matchup</h2><div class="g40-note">Matchup information lives here only. Lineup decisions stay in Lineup.</div></div></div><div class="g40-grid">${['QB','RB','WR','TE','DEF'].map(q=>`<div class="g40-card"><div class="g40-label">${q}</div>${ids().filter(id=>st().has(id)&&pos(id)===q).map(id=>playerRow(id)).join('')||'<div class="g40-empty">No starter</div>'}</div>`).join('')}</div></div>`}
function waivers(){const own=new Set(S.rosters.flatMap(r=>r.players||[]).map(String)),trend=new Map((S.adds||[]).map(x=>[String(x.player_id),n(x.count)])),a=Object.values(S.players||{}).filter(x=>{const id=String(x.player_id||'');return id&&!own.has(id)&&['QB','RB','WR','TE','DEF','DST'].includes(norm(x.position))}).map(x=>({id:String(x.player_id),v:proj(String(x.player_id)),t:n(trend.get(String(x.player_id)))})).sort((a,b)=>b.v-a.v||b.t-a.t).slice(0,25);return `<div class="g40-card"><div class="g40-title"><div><h2>Waiver GM</h2><div class="g40-note">One waiver board. Current projection first, trending adds second. Owned players are excluded.</div></div></div>${a.map((x,i)=>`<div class="g40-player"><div><span class="g40-slot">${i+1}</span><b>${esc(pname(x.id))}</b><span class="g40-muted">${pos(x.id)} · ${x.t||0} adds</span></div><strong>${x.v.toFixed(1)}</strong></div>`).join('')||'<div class="g40-empty">No waiver data available.</div>'}</div>`}
function placeholder(title,text){return `<div class="g40-card"><h2>${title}</h2><p class="g40-note">${text}</p><div class="g40-empty">Dedicated ${title.toLowerCase()} functionality will use this single surface. Legacy duplicate panels are disabled.</div></div>`}
function render(){const m=$('g40-main');if(!m)return;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));m.innerHTML=tab==='home'?home():tab==='lineup'?lineup():tab==='matchup'?matchupView():tab==='waivers'?waivers():tab==='trades'?placeholder('Trade Finder','Trade analysis belongs here and nowhere else.'):tab==='dynasty'?placeholder('Dynasty','Long-term roster value belongs here and nowhere else.'):placeholder('Roster','Your complete live roster belongs here and nowhere else.');$('g40-status').textContent=`Week ${n(S.week||S.league?.week,1)} · ${ids().length} players · ${ready?'GM ready':'loading'}`}
async function loadData(){ready=false;render();try{const w=n(S.week||S.league?.week,1),r=await fetch(`/api/research?season=${season}&week=${w}`,{cache:'no-store'});if(r.ok){const j=await r.json();projections=j.projections||{}}}catch(e){}try{const r=await fetch(`/api/nfl-schedule?season=${season}`,{cache:'no-store'});if(r.ok){const j=await r.json();schedule=Array.isArray(j)?j.map(g=>({...g,season:n(g.season,season),week:n(g.week),home_team:String(g.home_team||g.home||'').toUpperCase(),away_team:String(g.away_team||g.away||'').toUpperCase()})):[]}}catch(e){}ready=true;render()}
function boot(){css();hideOld();shell();loadData();setTimeout(()=>{hideOld();render()},1500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
